//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientWebApp.JourneyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://www.gre.ac.uk/pdc/na2880g/Quoter", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gre.ac.uk/pdc/na2880g/Quoter", ConfigurationName="JourneyService.JourneySearchSoap")]
    public interface JourneySearchSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://www.gre.ac.uk/pdc/na2880g/Quoter is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gre.ac.uk/pdc/na2880g/Quoter/HelloWorld", ReplyAction="*")]
        ClientWebApp.JourneyService.HelloWorldResponse HelloWorld(ClientWebApp.JourneyService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gre.ac.uk/pdc/na2880g/Quoter/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApp.JourneyService.HelloWorldResponse> HelloWorldAsync(ClientWebApp.JourneyService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name stn1 from namespace http://www.gre.ac.uk/pdc/na2880g/Quoter is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gre.ac.uk/pdc/na2880g/Quoter/GetDistance", ReplyAction="*")]
        ClientWebApp.JourneyService.GetDistanceResponse GetDistance(ClientWebApp.JourneyService.GetDistanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gre.ac.uk/pdc/na2880g/Quoter/GetDistance", ReplyAction="*")]
        System.Threading.Tasks.Task<ClientWebApp.JourneyService.GetDistanceResponse> GetDistanceAsync(ClientWebApp.JourneyService.GetDistanceRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://www.gre.ac.uk/pdc/na2880g/Quoter", Order=0)]
        public ClientWebApp.JourneyService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ClientWebApp.JourneyService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://www.gre.ac.uk/pdc/na2880g/Quoter", Order=0)]
        public ClientWebApp.JourneyService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ClientWebApp.JourneyService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gre.ac.uk/pdc/na2880g/Quoter")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistance", Namespace="http://www.gre.ac.uk/pdc/na2880g/Quoter", Order=0)]
        public ClientWebApp.JourneyService.GetDistanceRequestBody Body;
        
        public GetDistanceRequest() {
        }
        
        public GetDistanceRequest(ClientWebApp.JourneyService.GetDistanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gre.ac.uk/pdc/na2880g/Quoter")]
    public partial class GetDistanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string stn1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string stn2;
        
        public GetDistanceRequestBody() {
        }
        
        public GetDistanceRequestBody(string stn1, string stn2) {
            this.stn1 = stn1;
            this.stn2 = stn2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistanceResponse", Namespace="http://www.gre.ac.uk/pdc/na2880g/Quoter", Order=0)]
        public ClientWebApp.JourneyService.GetDistanceResponseBody Body;
        
        public GetDistanceResponse() {
        }
        
        public GetDistanceResponse(ClientWebApp.JourneyService.GetDistanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gre.ac.uk/pdc/na2880g/Quoter")]
    public partial class GetDistanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ClientWebApp.JourneyService.ArrayOfString GetDistanceResult;
        
        public GetDistanceResponseBody() {
        }
        
        public GetDistanceResponseBody(ClientWebApp.JourneyService.ArrayOfString GetDistanceResult) {
            this.GetDistanceResult = GetDistanceResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JourneySearchSoapChannel : ClientWebApp.JourneyService.JourneySearchSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JourneySearchSoapClient : System.ServiceModel.ClientBase<ClientWebApp.JourneyService.JourneySearchSoap>, ClientWebApp.JourneyService.JourneySearchSoap {
        
        public JourneySearchSoapClient() {
        }
        
        public JourneySearchSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JourneySearchSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JourneySearchSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JourneySearchSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApp.JourneyService.HelloWorldResponse ClientWebApp.JourneyService.JourneySearchSoap.HelloWorld(ClientWebApp.JourneyService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ClientWebApp.JourneyService.HelloWorldRequest inValue = new ClientWebApp.JourneyService.HelloWorldRequest();
            inValue.Body = new ClientWebApp.JourneyService.HelloWorldRequestBody();
            ClientWebApp.JourneyService.HelloWorldResponse retVal = ((ClientWebApp.JourneyService.JourneySearchSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApp.JourneyService.HelloWorldResponse> ClientWebApp.JourneyService.JourneySearchSoap.HelloWorldAsync(ClientWebApp.JourneyService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApp.JourneyService.HelloWorldResponse> HelloWorldAsync() {
            ClientWebApp.JourneyService.HelloWorldRequest inValue = new ClientWebApp.JourneyService.HelloWorldRequest();
            inValue.Body = new ClientWebApp.JourneyService.HelloWorldRequestBody();
            return ((ClientWebApp.JourneyService.JourneySearchSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClientWebApp.JourneyService.GetDistanceResponse ClientWebApp.JourneyService.JourneySearchSoap.GetDistance(ClientWebApp.JourneyService.GetDistanceRequest request) {
            return base.Channel.GetDistance(request);
        }
        
        public ClientWebApp.JourneyService.ArrayOfString GetDistance(string stn1, string stn2) {
            ClientWebApp.JourneyService.GetDistanceRequest inValue = new ClientWebApp.JourneyService.GetDistanceRequest();
            inValue.Body = new ClientWebApp.JourneyService.GetDistanceRequestBody();
            inValue.Body.stn1 = stn1;
            inValue.Body.stn2 = stn2;
            ClientWebApp.JourneyService.GetDistanceResponse retVal = ((ClientWebApp.JourneyService.JourneySearchSoap)(this)).GetDistance(inValue);
            return retVal.Body.GetDistanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClientWebApp.JourneyService.GetDistanceResponse> ClientWebApp.JourneyService.JourneySearchSoap.GetDistanceAsync(ClientWebApp.JourneyService.GetDistanceRequest request) {
            return base.Channel.GetDistanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClientWebApp.JourneyService.GetDistanceResponse> GetDistanceAsync(string stn1, string stn2) {
            ClientWebApp.JourneyService.GetDistanceRequest inValue = new ClientWebApp.JourneyService.GetDistanceRequest();
            inValue.Body = new ClientWebApp.JourneyService.GetDistanceRequestBody();
            inValue.Body.stn1 = stn1;
            inValue.Body.stn2 = stn2;
            return ((ClientWebApp.JourneyService.JourneySearchSoap)(this)).GetDistanceAsync(inValue);
        }
    }
}
